backend:
  name: git-gateway
  repo: master

publish_mode: editorial_workflow

media_folder: static/assets
public_folder: /assets
collections:
  - name: blog
    label: Blog
    folder: content/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: loginRequired, label: Login Required, widget:boolean }
      - { name: description, label: Description }
      - { name: body, label: Body, widget: markdown }
      - {
          name: "cover",
          label: "Featured Image",
          widget: "image",
          required: true,
        }
      - { name: "tags", label: "Tags", widget: "list", default: ["news"] }
      - { name: "author", label: "Author", widget: "select", options: ["eli"] }
